### ISSUE TITLE
Not Working at Fedora32

### ISSUE THREAD

**Issue by cabrerachaparro** [tester1969/pam-validity#1]
Hello,
I added to gdm-password, su and sudo. But when trying to log using password it doesn't too much time. I don't know where to look to check the issue.

**OS:** Fedora 32
**Hardware:** T480
**Device:** Bus 001 Device 016: ID 06cb:009a Synaptics, Inc.

Thanks

**Comment by tester1969** [comment]
# **cd /usr/local/bin/python-validity/**
root@localhost python-validity]# **python3**
Python 3.8.3 (default, May 29 2020, 00:00:00) 
[GCC 10.1.1 20200507 (Red Hat 10.1.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> **from prototype import** *
>>> **open9x()**
Opening sensor: 57K0 FM-3367-001   
Calibration data loaded from a file.
>>> **db.dump_all()**
 5: User S-1-5-21-394619333-3876782012-1672975908-3333 with 2 fingers:
     6: f5 (WINBIO_FINGER_UNSPECIFIED_POS_01)
     9: f6 (WINBIO_FINGER_UNSPECIFIED_POS_02)
 7: User S-1-5-21-394619333-3876782012-1672975908-3334 with 1 fingers:
     8: f6 (WINBIO_FINGER_UNSPECIFIED_POS_02)
>>> 

Give the commands in bold and check if the answers are similar to mine 1st.

**Comment by cabrerachaparro** [comment]
This is what I got

```
>>> from prototype import *
>>> open9x()
Opening sensor: 57K0 FM-3367-001   
Calibration data loaded from a file.
>>> db.dump_all()
>>> 

```
It seems I don't have a user but I ran pair.py command.

**Comment by tester1969** [comment]
User is not enrolled with pair command. The pair command is to pair the host (your computer) with the fingerprint reader (it is made with TLS keys.
You need to enroll a user, with the following command:

enroll(sid_from_string('S-1-5-21-394619333-3876782012-1672975908-3333'), 0xf5)

During the command you will need to put your finger many times, so that reader "learns" your fingerprint.

**Comment by cabrerachaparro** [comment]
I already added the fingerprint but having the same issue. I don't know if I have to add the auth to another instance. I have these

![image](https://user-images.githubusercontent.com/8990248/87171644-92af4900-c298-11ea-82fe-258fbc042f69.png)

**Comment by tester1969** [comment]
No, let's try only "su" 1st. Before you play with this, always have a shell open with root priviledges, so in case you mess up have some root shell open to clear mess up. Before you edit the su you should save the file. If su works everything else will work.
So, show me 

**cat su**

then try 

**su -**

Show me any possible messages it produces.
and

**journalctl -n 2000 |grep su**
**journalctl -n 2000 |grep pam**

**Comment by cabrerachaparro** [comment]
[dcabrera@ibmlaptop pam.d]$ cat su
```
#%PAM-1.0
auth            sufficient      pam_rootok.so
# Uncomment the following line to implicitly trust users in the "wheel" group.
#auth           sufficient      pam_wheel.so trust use_uid
# Uncomment the following line to require a user to be in the "wheel" group.
#auth           required        pam_wheel.so use_uid
auth            substack        system-auth
auth            include         postlogin
auth            sufficient      pam_validity.so
account         sufficient      pam_succeed_if.so uid = 0 use_uid quiet
account         include         system-auth
account         sufficient      pam_validity.so
password        include         system-auth
session         include         system-auth
session         include         postlogin
session         optional        pam_xauth.so
```

```
Jul 10 21:39:54 ibmlaptop su[22503]: pam_unix(su-l:auth): authentication failure; logname= uid=1000 euid=0 tty=pts/0 ruser=dcabrera rhost=  user=root
Jul 10 21:39:54 ibmlaptop audit[22556]: USER_AUTH pid=22556 uid=1000 auid=1000 ses=5 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 msg='op=PAM:authentication grantors=? acct="root" exe="/usr/bin/su" hostname=ibmlaptop addr=? terminal=pts/0 res=failed'
Jul 10 21:39:56 ibmlaptop su[22556]: FAILED SU (to root) dcabrera on pts/0
Jul 10 21:39:57 ibmlaptop audit[22503]: USER_AUTH pid=22503 uid=1000 auid=1000 ses=5 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 msg='op=PAM:authentication grantors=? acct="root" exe="/usr/bin/su" hostname=ibmlaptop addr=? terminal=pts/0 res=failed'
Jul 10 21:39:59 ibmlaptop su[22503]: FAILED SU (to root) dcabrera on pts/0

Jul 10 21:39:54 ibmlaptop su[22503]: pam_unix(su-l:auth): authentication failure; logname= uid=1000 euid=0 tty=pts/0 ruser=dcabrera rhost=  user=root

Jul 10 21:43:09 ibmlaptop sudo[22689]: pam_unix(sudo:auth): conversation failed
Jul 10 21:43:09 ibmlaptop audit[22700]: USER_AUTH pid=22700 uid=1000 auid=1000 ses=5 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 msg='op=PAM:authentication grantors=? acct="dcabrera" exe="/usr/bin/sudo" hostname=? addr=? terminal=/dev/pts/0 res=failed'
Jul 10 21:43:09 ibmlaptop sudo[22689]: pam_unix(sudo:auth): auth could not identify password for [dcabrera]
Jul 10 21:43:10 ibmlaptop audit[22700]: USER_CMD pid=22700 uid=1000 auid=1000 ses=5 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 msg='cwd="/usr/local/bin/python-validity" cmd="ls" exe="/usr/bin/sudo" terminal=pts/0 res=failed'
Jul 10 21:43:10 ibmlaptop audit[22689]: USER_AUTH pid=22689 uid=1000 auid=1000 ses=5 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 msg='op=PAM:authentication grantors=? acct="dcabrera" exe="/usr/bin/sudo" hostname=? addr=? terminal=/dev/pts/0 res=failed'
Jul 10 21:43:12 ibmlaptop audit[22689]: USER_CMD pid=22689 uid=1000 auid=1000 ses=5 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 msg='cwd="/usr/local/bin/python-validity" cmd="ls" exe="/usr/bin/sudo" terminal=pts/0 res=failed'

Jul 10 21:43:09 ibmlaptop sudo[22689]: pam_unix(sudo:auth): conversation failed
Jul 10 21:43:09 ibmlaptop sudo[22689]: pam_unix(sudo:auth): auth could not identify password for [dcabrera]
```

**Comment by tester1969** [comment]
try to put 1st line the
auth            sufficient      pam_validity.so

**Comment by cabrerachaparro** [comment]
> try to put 1st line the
> auth sufficient pam_validity.so

I did, but same issue.

**Comment by tester1969** [comment]
Is there a pam_validity.so in /usr/lib64/security/ ? 
It seems that pam_validity.so isn't called.
Give me "journalctl -n 20000 |grep pam" after you try again with su (not sudo)

**Comment by cabrerachaparro** [comment]
I did.
pam_validity.so is in /usr/lib64/security/ and **journalctl -n 20000 |grep pam** give me:

```
Jul 13 14:33:39 ibmlaptop su[85459]: pam_unix(su-l:auth): authentication failure; logname= uid=1000 euid=0 tty=pts/0 ruser=dcabrera rhost=  user=root
Jul 13 14:33:42 ibmlaptop su[85458]: pam_unix(su-l:auth): authentication failure; logname= uid=1000 euid=0 tty=pts/0 ruser=dcabrera rhost=  user=root
```

**Comment by tester1969** [comment]
Still ignores it. Should have something like this is in log

Jul 13 21:04:31 localhost.localdomain audit[479782]: CRED_REFR pid=479782 uid=0 auid=1000 ses=2 subj=system_u:system_r:xdm_t:s0-s0:c0.c1023 msg='op=PAM:setcred grantors=pam_validity acct="user1" exe="/usr/libexec/gdm-session-worker" hostname=localhost.localdomain addr=? terminal=/dev/tty1 res=success'

as shown, uses the pam_validity, yours uses pam_unix. 

I would remove any other entry and leave only pam_validity.so. 

Remember to have a terminal open in root in case su fails, so you  are able to change it back, or do any other modifications.
Does the white LED lights on when you issue the "su" commad?

**Comment by tester1969** [comment]
BTW this is mine:

auth		sufficient	pam_validity.so
auth		sufficient	pam_rootok.so
auth		substack	system-auth
auth		include		postlogin
account 	sufficient 	pam_validity.so
account		include		system-auth
password	include		system-auth
session		include		system-auth
session		include		postlogin
session		optional	pam_xauth.so

**Comment by cabrerachaparro** [comment]
It didn't work. :( I think it is related to this line `auth substack system-auth` because when I comment it su doesn't work either it says **permission denied.**

What do you have in file system-auth?

**Comment by tester1969** [comment]
I haven't touch system-auth but ere it is
auth        required                                     pam_env.so
auth        required                                     pam_faildelay.so delay=2000000
auth        [default=1 ignore=ignore success=ok]         pam_usertype.so isregular
auth        [default=1 ignore=ignore success=ok]         pam_localuser.so
auth        sufficient                                   pam_unix.so nullok try_first_pass
auth        [default=1 ignore=ignore success=ok]         pam_usertype.so isregular
auth        sufficient                                   pam_sss.so forward_pass
auth        required                                     pam_deny.so

account     required                                     pam_unix.so
account     sufficient                                   pam_localuser.so
account     sufficient                                   pam_usertype.so issystem
account     [default=bad success=ok user_unknown=ignore] pam_sss.so
account     required                                     pam_permit.so

password    requisite                                    pam_pwquality.so try_first_pass local_users_only
password    sufficient                                   pam_unix.so sha512 shadow nullok try_first_pass use_authtok
password    sufficient                                   pam_sss.so use_authtok
password    required                                     pam_deny.so

session     optional                                     pam_keyinit.so revoke
session     required                                     pam_limits.so
-session    optional                                     pam_systemd.so
session     [success=1 default=ignore]                   pam_succeed_if.so service in crond quiet use_uid
session     required                                     pam_unix.so
session     optional                                     pam_sss.so

**Comment by cabrerachaparro** [comment]
Yes, it is the same. I can't find what is wrong.

**Comment by tester1969** [comment]
I uploaded a debug version to make sure that problem is not in my code.
Install it with

ld -x --shared -o /usr/lib64/security/pam_validity_debug.so pam_validity_debug.o

gcc -fPIC -fno-stack-protector -c pam_validity_debug.c

and put it in your /etc/pam.d/su file

If it is called it will print messages

**Comment by jsmpereira** [comment]
@tester1969 Thank you for providing the pam module.

I've been following the discussion here and in https://github.com/uunicorn/python-validity/issues/3.

I was able to update `/etc/pam.d/su` accordingly. I am however getting `usb.core.USBError: [Errno 16] Resource busy`.

```
/etc/pam.d >>> su                                                                                   
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/usr/lib/python3.8/site-packages/validitysensor/init.py", line 47, in open
    open_common()
  File "/usr/lib/python3.8/site-packages/validitysensor/init.py", line 29, in open_common
    init_flash()
  File "/usr/lib/python3.8/site-packages/validitysensor/init_flash.py", line 107, in init_flash
    info = get_flash_info()
  File "/usr/lib/python3.8/site-packages/validitysensor/flash.py", line 28, in get_flash_info
    rsp=tls.cmd(unhex('3e'))
  File "/usr/lib/python3.8/site-packages/validitysensor/tls.py", line 119, in cmd
    rsp=self.usb.cmd(cmd)
  File "/usr/lib/python3.8/site-packages/validitysensor/usb.py", line 93, in cmd
    self.dev.write(1, out)
  File "/usr/lib/python3.8/site-packages/usb/core.py", line 940, in write
    intf, ep = self._ctx.setup_request(self, endpoint)
  File "/usr/lib/python3.8/site-packages/usb/core.py", line 102, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/usb/core.py", line 216, in setup_request
    self.managed_claim_interface(device, intf)
  File "/usr/lib/python3.8/site-packages/usb/core.py", line 102, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/usb/core.py", line 167, in managed_claim_interface
    self.backend.claim_interface(self.handle, i)
  File "/usr/lib/python3.8/site-packages/usb/backend/libusb1.py", line 811, in claim_interface
    _check(self.lib.libusb_claim_interface(dev_handle.handle, intf))
  File "/usr/lib/python3.8/site-packages/usb/backend/libusb1.py", line 595, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 16] Resource busy
Password:
```

I also get the same error if I try to run `open9x()`:

```
Python 3.8.3 (default, May 17 2020, 18:15:42) 
[GCC 10.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from prototype import *
>>> open9x()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.8/site-packages/validitysensor/init.py", line 47, in open
    open_common()
  File "/usr/lib/python3.8/site-packages/validitysensor/init.py", line 29, in open_common
    init_flash()
  File "/usr/lib/python3.8/site-packages/validitysensor/init_flash.py", line 107, in init_flash
    info = get_flash_info()
  File "/usr/lib/python3.8/site-packages/validitysensor/flash.py", line 28, in get_flash_info
    rsp=tls.cmd(unhex('3e'))
  File "/usr/lib/python3.8/site-packages/validitysensor/tls.py", line 119, in cmd
    rsp=self.usb.cmd(cmd)
  File "/usr/lib/python3.8/site-packages/validitysensor/usb.py", line 93, in cmd
    self.dev.write(1, out)
  File "/usr/lib/python3.8/site-packages/usb/core.py", line 940, in write
    intf, ep = self._ctx.setup_request(self, endpoint)
  File "/usr/lib/python3.8/site-packages/usb/core.py", line 102, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/usb/core.py", line 216, in setup_request
    self.managed_claim_interface(device, intf)
  File "/usr/lib/python3.8/site-packages/usb/core.py", line 102, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/usb/core.py", line 167, in managed_claim_interface
    self.backend.claim_interface(self.handle, i)
  File "/usr/lib/python3.8/site-packages/usb/backend/libusb1.py", line 811, in claim_interface
    _check(self.lib.libusb_claim_interface(dev_handle.handle, intf))
  File "/usr/lib/python3.8/site-packages/usb/backend/libusb1.py", line 595, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 16] Resource busy
```

Any idea about this behaviour?

**Comment by cabrerachaparro** [comment]
@jsmpereira I solved that rebooting the laptop.

**Comment by cabrerachaparro** [comment]
@tester1969 I got this
```
Reached step 1Child pid is 0
Welcome root
Password: 
```

**Comment by tester1969** [comment]
there is hope. It means pam does really calls our module. I will prepare a more detailed version of our module and a debug version  of .sh file and we will try again. For  now, give me a "ls -l /usr/local/bin/python-validity"

@jsmpereira I usually get this when the fingerprint device is really busy by some other unfisnished or stalled process. Reboot does gets rid of the problem. In general what it says there is true. Something is keeping busy of the device.

**Comment by tester1969** [comment]
I uploaded a "debug" version of pam_validity.sh, named pam_validity_debug.sh. Download it, and replace the /usr/local/bin/python-validity/pam_validity.sh with this (In the end it must have the same name, not pam_validity_debug.sh) run the process and post me results

**Comment by cabrerachaparro** [comment]
I ran the first time and didn't work but I realized that pam_validity.sh didn't have execution permission. I gave the access an then ran it again and got this:

```
Reached step 1Child pid is 0
Hi reached sh
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/usb/core.py", line 223, in get_interface_and_endpoint
    return self._ep_info[endpoint_address]
KeyError: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/usr/local/bin/python-validity/validitysensor/init.py", line 22, in open
    usb.send_init()
  File "/usr/local/bin/python-validity/validitysensor/usb.py", line 59, in send_init
    assert_status(self.cmd(unhexlify('01')))
  File "/usr/local/bin/python-validity/validitysensor/usb.py", line 80, in cmd
    self.dev.write(1, out)
  File "/usr/local/lib/python3.8/site-packages/usb/core.py", line 940, in write
    intf, ep = self._ctx.setup_request(self, endpoint)
  File "/usr/local/lib/python3.8/site-packages/usb/core.py", line 102, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/usb/core.py", line 215, in setup_request
    intf, ep = self.get_interface_and_endpoint(device, endpoint_address)
  File "/usr/local/lib/python3.8/site-packages/usb/core.py", line 102, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/usb/core.py", line 225, in get_interface_and_endpoint
    for intf in self.get_active_configuration(device):
  File "/usr/local/lib/python3.8/site-packages/usb/core.py", line 102, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/usb/core.py", line 236, in get_active_configuration
    self.managed_open()
  File "/usr/local/lib/python3.8/site-packages/usb/core.py", line 102, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/usb/core.py", line 120, in managed_open
    self.handle = self.backend.open_device(self.dev)
  File "/usr/local/lib/python3.8/site-packages/usb/backend/libusb1.py", line 786, in open_device
    return _DeviceHandle(dev)
  File "/usr/local/lib/python3.8/site-packages/usb/backend/libusb1.py", line 643, in __init__
    _check(_lib.libusb_open(self.devid, byref(self.handle)))
  File "/usr/local/lib/python3.8/site-packages/usb/backend/libusb1.py", line 595, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 13] Access denied (insufficient permissions)

Failure!
Welcome root
```

And this is the **ls** result:

```
ls -l /usr/local/bin/python-validity
total 7380
-rw-r--r--. 1 root root  218482 Jul  9 13:46 6_07f_lenovo_mis_qm.xpfwext
-rw-r--r--. 1 root root   13440 Jul 13 18:54 calib-data.bin
drwxr-xr-x. 3 root root    4096 Jul  9 13:46 codeGetExtractPath
-rw-r--r--. 1 root root    4938 Jul  9 13:46 dbus-service.py
-rw-r--r--. 1 root root     112 Jul  9 13:46 factory-reset.py
-rw-r--r--. 1 root root    1797 Jul  9 13:46 led-dance.py
-rw-r--r--. 1 root root    1065 Jul  9 13:46 LICENSE
-rw-r--r--. 1 root root 7244088 Jul  9 13:46 nz3gf07w.exe
-rw-r--r--. 1 root root     903 Jul  9 13:46 pair.py
-rwxr--r--. 1 root root     493 Jul 15 10:06 pam_validity.sh
-rw-r--r--. 1 root root    1768 Jul  9 13:46 prototype.py
drwxr-xr-x. 2 root root    4096 Jul 10 09:43 __pycache__
-rw-r--r--. 1 root root    9254 Jul  9 13:46 README.md
-rw-r--r--. 1 root root      34 Jul  9 13:46 requirements.txt
drwxr-xr-x. 3 root root    4096 Jul  9 13:46 validitysensor
-rw-r--r--. 1 root root    8725 Jul  9 13:46 validity-sensors-initializer.py
```

**Comment by cabrerachaparro** [comment]
It worked!!!

I create a new file **/etc/udev/rules.d/99-usbftdi.rules** with this line
`SUBSYSTEM=="usb", ATTRS{idVendor}=="06cb", MODE="0666"
`
Then run the following command to restart udev rules
`# udevadm control --reload-rules && udevadm trigger`

Thanks for all your work!!!
